mulan/controllers/college.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, abort, request
from leancloud import Query, Object

from ..models import BaseQuery

__author__ = 'Simi'
__all__ = ['bp']
bp = Blueprint('college', __name__)

type_to_name = {1: '桂电要闻',
                2: '校园快讯',
                4: '校内通知',
                6: '学术会议',
                8: '学院动态',
                9: '媒体桂电',
                10: '公 告'}


@bp.route("/", methods=['GET'])
def index():
    page = int(request.args.get('page', 1))
    if not page:
        return abort(404)
    paginator = BaseQuery(query_class='College', descend_key='news_time').paginate(page, 20)
    return render_template('college/index.html', paginator=paginator,
                           endpoint='college.index')


@bp.route(u'/type=<news_type>', methods=['GET'])
def index_type(news_type):
    if news_type is None:
        news_type = 1
    else:
        news_type = int(news_type)
    page = int(request.args.get('page', 1))
    if not page:
        return abort(404)
    paginator = BaseQuery('College', news_type, 'news_time').paginate(page, 20)
    return render_template('college/index_type.html', paginator=paginator,
                           endpoint='college.index_type', news_type=news_type,
                           news_title=type_to_name[news_type])


@bp.route('/<id>', methods=['GET'])
def content(id):
    if id is None:
        abort(404)
    news = Query(Object.extend('College')).get(id)
    print news.created_at
    return render_template('college/content.html', news=news)

mulan/controllers/front.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, jsonify, json, request
from leancloud import Object, Query

__author__ = 'Simi'
__all__ = ['bp']
bp = Blueprint('front', __name__)


@bp.route('/')
def index():
    college_news = Query(Object.extend('College')).descending(key='news_time'). \
        limit(10).select('news_title', 'news_time').find()

    work_news = Query(Object.extend('Work')).descending(key='news_time'). \
        limit(10).select('news_title', 'news_time').find()

    notice_news = Query(Object.extend('College')).equal_to(key='news_type', value=10).\
        descending(key='news_time').limit(10).select('news_title', 'news_time').find()

    recruit_news = Query(Object.extend('Work')).equal_to(key='news_type', value=16).\
        descending(key='news_time').limit(10).select('news_title', 'news_time').find()

    return render_template('front/index.html', college_news=college_news, work_news=work_news,
                           notice_news=notice_news, recruit_news=recruit_news)

mulan/controllers/work.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, abort, request
from leancloud import Query, Object

from ..models import BaseQuery

__author__ = 'Simi'
__all__ = ['bp']
bp = Blueprint('work', __name__)

type_to_name = {3: '就业公告',
                4: '就业新闻',
                13: '每周来校招聘单位',
                15: '用人单位来校招聘信息发布',
                16: '用人单位网络招聘信息发布'
                }


@bp.route('/')
def index():
    page = int(request.args.get('page', 1))
    if not page:
        return abort(404)
    paginator = BaseQuery(query_class='Work', descend_key='news_time').paginate(page, 20)
    return render_template('work/index.html', paginator=paginator,
                           endpoint='work.index')


@bp.route('/news_type=<news_type>')
def index_type(news_type):
    if news_type is None:
        news_type = 1
    else:
        news_type = int(news_type)
    page = int(request.args.get('page', 1))
    if not page:
        return abort(404)
    paginator = BaseQuery('Work', news_type, 'news_time').paginate(page, 20)
    return render_template('work/index_type.html', paginator=paginator,
                           endpoint='work.index_type', news_type=news_type,
                           news_title=type_to_name.get(news_type))


@bp.route('/news_id=<id>', methods=['GET'])
def content(id):
    if id is None:
        abort(404)
    news = Query(Object.extend('Work')).get(id)
    return render_template('work/content.html', news=news)

mulan/templates/front/index.html
{% extends "layout.html" %}

{% block subtitle %}
    欢迎访问桂林电子科技大学新闻汇总平台
{% endblock %}

{% block content %}
    <section class="panel">
        <div class="panel-body">
            <div class="btn-row">
                    <a type="button" class="btn btn-primary" href="{{ url_for('college.index') }}">校园主页</a>:
                    <a type="button" class="btn btn-info" href="{{ url_for('college.index_type', news_type=1) }}">桂电要闻</a>
                    <a type="button" class="btn btn-info" href="{{ url_for('college.index_type', news_type=2) }}">校园快讯</a>
                    <a type="button" class="btn btn-info" href="{{ url_for('college.index_type', news_type=4) }}">校内通知</a>
                    <a type="button" class="btn btn-info" href="{{ url_for('college.index_type', news_type=6) }}">学术会议</a>
                    <a type="button" class="btn btn-info" href="{{ url_for('college.index_type', news_type=8) }}">学院动态</a>
                    <a type="button" class="btn btn-info" href="{{ url_for('college.index_type', news_type=9) }}">媒体桂电</a>
                    <a type="button" class="btn btn-info" href="{{ url_for('college.index_type', news_type=10) }}">公  告</a>
                </div>
            <div class="btn-row">
                    <a type="button" class="btn btn-primary" href="{{ url_for('work.index') }}">毕业生就业网</a>:
                    <a type="button" class="btn btn-info" href="{{ url_for('work.index_type', news_type=3) }}">就业公告</a>
                    <a type="button" class="btn btn-info" href="{{ url_for('work.index_type', news_type=4) }}">就业新闻</a>
                    <a type="button" class="btn btn-info" href="{{ url_for('work.index_type', news_type=13) }}">每周来校招聘单位</a>
                    <a type="button" class="btn btn-info" href="{{ url_for('work.index_type', news_type=15) }}">用人单位来校招聘信息</a>
                    <a type="button" class="btn btn-info" href="{{ url_for('work.index_type', news_type=16) }}">用人单位网络招聘信息</a>
                </div>
            </div>
    </section>

    <div class="row" xmlns="http://www.w3.org/1999/html">
        <div class="col-sm-6">
            <div class="panel">
                <div class="panel-heading">
                    校内新闻
                            <span class="tools pull-right">
                                <a href="javascript:;" class="fa fa-chevron-down"></a>
                            </span>
                </div>
                <div class="panel-body">
                    <table class="table">
                        {% if college_news %}
                            <thead>
                            <tr>
                                <th>标题</th>
                                <th>时间</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in college_news %}
                                <tr>
                                    <td>
                                        <a href="{{ url_for('college.content', id=item.id) }}">{{ item.get('news_title')|safe }}</a>
                                    </td>
                                    <td>
                                        {{ item.get('news_time')|_datetime }}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="panel">
                <div class="panel-heading">
                    公告
                            <span class="tools pull-right">
                                <a href="javascript:;" class="fa fa-chevron-down"></a>
                            </span>
                </div>
                <div class="panel-body">
                    <table class="table">
                        {% if college_news %}
                            <thead>
                            <tr>
                                <th>标题</th>
                                <th>时间</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in notice_news %}
                                <tr>
                                    <td>
                                        <a href="{{ url_for('college.content', id=item.id) }}">{{ item.get('news_title')|safe }}</a>
                                    </td>
                                    <td>
                                        {{ item.get('news_time')|_datetime }}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-6">
            <div class="panel">
                <div class="panel-heading">
                    招聘信息
                            <span class="tools pull-right">
                                <a href="javascript:;" class="fa fa-chevron-down"></a>
                            </span>
                </div>
                <div class="panel-body">
                    <table class="table">
                        {% if recruit_news %}
                            <thead>
                            <tr>
                                <th>标题</th>
                                <th>时间</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in recruit_news %}
                                <tr>
                                    <td>
                                        <a href="{{ url_for('work.content', id=item.id) }}">{{ item.get('news_title')|safe }}</a>
                                    </td>
                                    <td>
                                        {{ item.get('news_time')|_datetime }}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="panel">
                <div class="panel-heading">
                    就业网最新信息
                            <span class="tools pull-right">
                                <a href="javascript:;" class="fa fa-chevron-down"></a>
                            </span>
                </div>
                <div class="panel-body">
                    <table class="table">
                        {% if work_news %}
                            <thead>
                            <tr>
                                <th>标题</th>
                                <th>时间</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in work_news %}
                                <tr>
                                    <td>
                                        <a href="{{ url_for('work.content', id=item.id) }}">{{ item.get('news_title')|safe }}</a>
                                    </td>
                                    <td>
                                        {{ item.get('news_time')|_datetime }}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>

{% endblock %}