mulan/models/college.py
from leancloud import Object, Query
from flask import _request_ctx_stack, abort, has_request_context, request

__all__ = ['College']


class College(Object):

    @property
    def news_time(self):
        return self.get('news_time')

    @news_time.setter
    def news_time(self, value):
        return self.set('news_time', value)

    @property
    def news_url(self):
        return self.get('news_url')

    @news_url.setter
    def news_url(self, value):
        return self.set('news_url', value)

    @property
    def news_title(self):
        return self.get('news_title')

    @news_title.setter
    def news_title(self, value):
        return self.set('news_title', value)

    @property
    def news_content(self):
        return self.get('news_content')

    @news_content.setter
    def news_content(self, value):
        return self.set('news_content', value)

    @property
    def news_type(self):
        return self.get('news_type')

    @news_type.setter
    def news_type(self, value):
        return self.set('news_type', value)

    @property
    def news_attachment(self):
        return self.get('news_attachment')

    @news_attachment.setter
    def news_attachment(self, value):
        return self.set('news_attachment', value)

    @property
    def news_other(self):
        return self.get('news_other')

    @news_other.setter
    def news_other(self, value):
        return self.set('news_other', value)

    @staticmethod
    def get(id):
        try:
            return Query('College').get(id)
        except:
            return None

mulan/controllers/college.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, abort, request
from leancloud import Query, Object

from ..models import BaseQuery

__author__ = 'Simi'
__all__ = ['bp']
bp = Blueprint('college', __name__)

type_to_name = {1: '桂电要闻',
                2: '校园快讯',
                4: '校内通知',
                6: '学术会议',
                8: '学院动态',
                9: '媒体桂电',
                10: '公 告'}


@bp.route("/", methods=['GET'])
def index():
    page = int(request.args.get('page', 1))
    if not page:
        return abort(404)
    paginator = BaseQuery(query_class='College', descend_key='news_time').paginate(page, 20)
    return render_template('college/index.html', paginator=paginator,
                           endpoint='college.index')


@bp.route(u'/type=<news_type>', methods=['GET'])
def index_type(news_type):
    if news_type is None:
        news_type = 1
    else:
        news_type = int(news_type)
    page = int(request.args.get('page', 1))
    if not page:
        return abort(404)
    paginator = BaseQuery('College', news_type, 'news_time').paginate(page, 20)
    return render_template('college/index_type.html', paginator=paginator,
                           endpoint='college.index_type', news_type=news_type,
                           news_title=type_to_name[news_type])


@bp.route('/<id>', methods=['GET'])
def content(id):
    if id is None:
        abort(404)
    news = Query(Object.extend('College')).get(id)
    print news.created_at
    return render_template('college/content.html', news=news)

mulan/controllers/front.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, jsonify, json, request
from leancloud import Object, Query

__author__ = 'Simi'
__all__ = ['bp']
bp = Blueprint('front', __name__)


@bp.route('/')
def index():
    college_news = Query(Object.extend('College')).descending(key='news_time'). \
        limit(10).select('news_title', 'news_time').find()

    work_news = Query(Object.extend('Work')).descending(key='news_time'). \
        limit(10).select('news_title', 'news_time').find()

    notice_news = Query(Object.extend('College')).equal_to(key='news_type', value=10).\
        descending(key='news_time').limit(10).select('news_title', 'news_time').find()

    recruit_news = Query(Object.extend('Work')).equal_to(key='news_type', value=16).\
        descending(key='news_time').limit(10).select('news_title', 'news_time').find()

    return render_template('front/index.html', college_news=college_news, work_news=work_news,
                           notice_news=notice_news, recruit_news=recruit_news)

mulan/templates/college/content.html
{% extends "layout.html" %}

{% block subtitle %}{{ news.get('news_title') }}{% endblock %}

{% from "snippet/macro.html" import navigation, topic_columns, pagination %}


{% block content %}
    <section class="panel panel-info">
        <header class="panel-heading">
            <div class="panel-title" align="center">
                <strong>{{ news.get('news_title') }}</strong>
            </div>

        </header>
        <div class="panel-body">
            <div align="center">发布时间：{{ news.get('news_time')|safe }}</div>
            <div class="content">{{ news.get('news_content')|safe }}</div>

        </div>
        <div class="panel-footer panel-info" align="right">
            <a href="{{ news.get('news_url')|safe }}">查看原文</a>
        </div>
    </section>
{% endblock %}

mulan/templates/college/index.html
{% extends "layout.html" %}

{% block subtitle %}
    校内新闻
{% endblock %}
{% from "snippet/macro.html" import navigation, pagination %}


{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <!--breadcrumbs start -->
            <ul class="breadcrumb">
                <li><a href="{{ url_for('front.index') }}"><i class="fa fa-home"></i> 主页</a></li>
                <li><a class="active">校园新闻</a></li>
            </ul>
            <!--breadcrumbs end -->
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="panel">
                <div class="panel-heading">
                    校内新闻
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-advance table-hover">
                        {% if paginator.items %}
                            <thead>
                            <tr>
                                <th>新闻标题</th>
                                <th>新闻类型</th>
                                <th>发布时间</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in paginator.items %}
                                <tr>
                                    <td><a href="{{ url_for('college.content', id=item.id ) }}">{{ item.get('news_title')|safe }}</a></td>
                                    <td>{{ item.get('news_type')|college_type}} </td>
                                    <td>{{ item.get('news_time')|_datetime }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>

                        {% endif %}

                    </table>
                    {% if paginator.pages >1 %}
                        {{ pagination(paginator, url_for(endpoint, news_type=news_type)) }}
                    {% endif %}
                </div>

            </div>
        </div>


        <div class="col-md-3">
            <div class="fb-timeliner">
                <h2 class="recent-highlight">Recent</h2>
                <ul>
                    <li class="active"><a href="#">December</a></li>
                    <li><a href="#">November</a></li>
                    <li><a href="#">October</a></li>
                    <li><a href="#">September</a></li>
                    <li><a href="#">August</a></li>
                    <li><a href="#">July</a></li>
                    <li><a href="#">June</a></li>
                    <li><a href="#">May</a></li>
                    <li><a href="#">April</a></li>
                    <li><a href="#">March</a></li>
                    <li><a href="#">February</a></li>
                    <li><a href="#">January</a></li>
                </ul>
            </div>
            <div class="fb-timeliner">
                <h2>2012</h2>
                <ul>
                    <li><a href="#">August</a></li>
                    <li><a href="#">July</a></li>
                    <li><a href="#">June</a></li>
                    <li><a href="#">May</a></li>
                    <li><a href="#">April</a></li>
                    <li><a href="#">March</a></li>
                    <li><a href="#">February</a></li>
                    <li><a href="#">January</a></li>
                </ul>
            </div>

            <div class="fb-timeliner">
                <h2>2011</h2>
                <ul>
                    <li><a href="#">May</a></li>
                    <li><a href="#">April</a></li>
                    <li><a href="#">March</a></li>
                    <li><a href="#">February</a></li>
                    <li><a href="#">January</a></li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

mulan/templates/college/index_type.html
{% extends "layout.html" %}

{% block subtitle %}{{news_title }}{% endblock %}
{% from "snippet/macro.html" import navigation, pagination %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <!--breadcrumbs start -->
            <ul class="breadcrumb">
                <li><a href="{{ url_for('front.index') }}"><i class="fa fa-home"></i> 主页</a></li>
                <li><a href="{{ url_for('college.index') }}">校园新闻</a></li>
                <li><a href="#">{{ news_title }}</a></li>
            </ul>
            <!--breadcrumbs end -->
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="panel">
                <div class="panel-heading">
                    {{ news_title }}
                </div>
                <div class="panel-body">
                    <table class="table table-striped table-advance table-hover">
                        {% if paginator.items %}
                            <thead>
                            <tr>
                                <th>新闻标题</th>
                                <th>发布时间</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in paginator.items %}
                                <tr>
                                    <td><a href="{{ url_for('college.content', id=item.id ) }}">{{ item.get('news_title')|safe }}</a></td>
                                    <td>{{ item.get('news_time')|_datetime }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>

                        {% endif %}

                    </table>
                    {% if paginator.pages >1 %}
                        {{ pagination(paginator, url_for(endpoint, news_type=news_type)) }}
                    {% endif %}
                </div>

            </div>
        </div>


        <div class="col-md-3">
            <div class="fb-timeliner">
                <h2 class="recent-highlight">Recent</h2>
                <ul>
                    <li class="active"><a href="#">December</a></li>
                    <li><a href="#">November</a></li>
                    <li><a href="#">October</a></li>
                    <li><a href="#">September</a></li>
                    <li><a href="#">August</a></li>
                    <li><a href="#">July</a></li>
                    <li><a href="#">June</a></li>
                    <li><a href="#">May</a></li>
                    <li><a href="#">April</a></li>
                    <li><a href="#">March</a></li>
                    <li><a href="#">February</a></li>
                    <li><a href="#">January</a></li>
                </ul>
            </div>
            <div class="fb-timeliner">
                <h2>2012</h2>
                <ul>
                    <li><a href="#">August</a></li>
                    <li><a href="#">July</a></li>
                    <li><a href="#">June</a></li>
                    <li><a href="#">May</a></li>
                    <li><a href="#">April</a></li>
                    <li><a href="#">March</a></li>
                    <li><a href="#">February</a></li>
                    <li><a href="#">January</a></li>
                </ul>
            </div>

            <div class="fb-timeliner">
                <h2>2011</h2>
                <ul>
                    <li><a href="#">May</a></li>
                    <li><a href="#">April</a></li>
                    <li><a href="#">March</a></li>
                    <li><a href="#">February</a></li>
                    <li><a href="#">January</a></li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}