mulan/controllers/account.py
# -*- coding: utf-8 -*-
from flask import Blueprint, request, render_template, abort, jsonify, redirect, \
    url_for, g, flash, current_app
from ..utils.user import login_user, logout_user, verify_auth_token, require_login
from ..forms import SigninForm, SignupForm, ChangePasswordForm, FindForm
from ..utils.mail import signup_mail, find_mail

__author__ = 'Simi'
__all__ = ['bp']

bp = Blueprint('account', __name__)


# @bp.errorhandler(Exception)
# def handle_exception(e):
#     # TODO: LOG
#     traceback.print_exc()
#     # flash('You give us a problem, we will solve as soon as possible.', 'error')
#     abort(501)

@bp.route('/')
@bp.route('/signin', methods=['GET', 'POST'])
def signin():
    """Sign in page."""
    # next_url = request.args.get('next', url_for('front.index'))
    next_url = request.args.get('next', url_for('admin.index'))
    if g.user:
        return redirect(next_url)
    form = SigninForm()
    if form.validate_on_submit():
        login_user(form.user, form.permanent.data)
        return redirect(next_url)
    return render_template('account/signin.html', form=form, next_url=next_url)


@bp.route('/signout')
def signout():
    """Sign out, and redirect."""
    next_url = request.args.get('next', url_for('account.signin'))
    logout_user()
    return redirect(next_url)


@bp.route('/signup', methods=['GET', 'POST'])
def signup():
    """Sign up page. If the request has an token arguments, it is not
    for registeration, it is for verifying the token.
    """
    next_url = request.args.get('next', url_for('front.index'))
    token = request.args.get('token')
    if token:
        user = verify_auth_token(token, 1)
        if not user:
            flash('Invalid or expired token.', 'error')
            return redirect(next_url)
        user.role = 'user'
        user.save()
        login_user(user)
        flash('This account is verified.', 'success')
        return redirect(next_url)

    form = SignupForm()
    if form.validate_on_submit():
        verify_email = current_app.config.get('VERIFY_EMAIL', True)
        if not verify_email:
            # if no need for verify email
            # we should save the role as new
            user = form.save('new')
            login_user(user)
            return redirect(next_url)
        user = form.save('new')
        login_user(user)
        # msg = signup_mail(user)
        # if current_app.debug:
        #     return msg.html
        # flash('We have sent you an activate email, check your inbox.','info')
        return redirect(next_url)
    return render_template('account/signup.html', form=form)


@bp.route('/setting', methods=['GET', 'POST'])
@require_login
def setting():
    """Settings page of current user."""
    form = ChangePasswordForm()
    return render_template('account/setting.html', password_form=form)


@bp.route('/password', methods=['GET', 'POST'])
@require_login
def change_password():
    """Change password page."""
    form = ChangePasswordForm()
    if form.validate_on_submit():
        flag = g.user.check_password(form.old_password.data)
        if flag:
            g.user.change_password(form.new_password.data).save()
            login_user(g.user)
            flash('密码已修改，请牢记修改后的新密码。', 'success')
            return redirect(url_for('.setting'))
        else:
            flash('密码修改失败，请稍后重试。', 'error')
    return render_template('account/setting.html', password_form=form)


@bp.route('/find', methods=['GET', 'POST'])
def find():
    """重置密码"""
    if g.user:
        return redirect('/')
    form = FindForm()
    if form.validate_on_submit():
        msg = find_mail(form.user)
        if current_app.debug or current_app.testing:
            return msg.html
        flash('邮件发送成功', 'info')
        return redirect(url_for('.signin'))
    return render_template('account/find.html', form=form)

mulan/controllers/admin.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, abort, jsonify, request, redirect, url_for, g, \
    flash, current_app

from leancloud import Query

from ..utils.user import require_login, require_admin
from ..models import Account
from ..forms import SearchAccountForm, EditAccountForm
from ..utils.helpers import force_int

__author__ = 'Simi'
__all__ = ['bp']
bp = Blueprint('admin', __name__)


@bp.route('/')
@require_login
def index():
    return render_template('admin/index_type.html')


@bp.route('/user')
@require_login
@require_admin
def user():
    page = force_int(request.args.get('page', 1), 1)
    page_size = 10

    q = Query("_User")

    search_form = SearchAccountForm()

    keyword = None
    if request.method == 'GET':
        search_form.keyword.data = keyword = request.args.get('keyword', '')

    if search_form.validate_on_submit():
        keyword = search_form.keyword.data.strip()

    if keyword:
        if "@" in keyword:
            q = q.startswith("email", keyword)
        else:
            q = q.startswith("username", keyword)

    users = q.skip((page - 1) * page_size).limit(page_size).find()
    count = q.count()
    pages = count / page_size + 1

    return render_template('admin/user.html', users=users, form=search_form, count=count, pages=pages, page=page)


@bp.route('/user/edit/<string:id>', methods=['GET', 'POST'])
@require_login
@require_admin
def edit_user(id):
    user = Account.get(id)
    if not user:
        abort(404)
    form = EditAccountForm(obj=user)

    if form.validate_on_submit():
        user.set('state', form.state.data)
        user.set('roles', [form.role.data])
        user.save()
        flash('用户 %s 的信息已成功保存' % user.get('username'), 'success')
        return redirect(url_for('.user'))
    else:
        roles = user.get('roles')
        if roles:
            # 当前仅支持一个用户拥有一种角色
            form.role.data = roles[0]
        state = user.get('state')
        if state:
            form.state.data = state
    return render_template('admin/edit_user.html', form=form, user=user)

mulan/templates/snippet/footer.html
<footer id="footer">
  <div class="container clearfix">
    <div class="text-muted pull-left">
      <a href="/about">About</a>
      <span class="sep">|</span>
    </div>
    <p class="muted credit copyright">
    &copy;<time datetime="{{config.SITE_TIME}}">{{config.SITE_TIME.year}}</time> {{config.SITE_TITLE}}.
    </p>
  </div>
</footer>

mulan/templates/snippet/macro.html
{% macro admin_menu(current='dashboard') %}
  <!--sidebar start-->
  <aside>
      <div id="sidebar"  class="nav-collapse ">
          <!-- sidebar menu start-->
          <ul class="sidebar-menu" id="nav-accordion">
              <li>
                  <a {% if current == 'dashboard' %}class="active"{% endif %} href="{{ url_for('admin.index') }}">
                      <i class="fa fa-dashboard"></i>
                      <span>控制台</span>
                  </a>
              </li>
              {% if 'admin' in g.user.get('roles') %}
              <li>
                  <a {% if current == 'user' %}class="active"{% endif %} href="{{ url_for('admin.user') }}">
                      <i class="fa fa-user"></i>
                      <span>用户管理</span>
                  </a>
              </li>
              {% endif %}
              <li>
                  <a {% if current == 'setting' %}class="active"{% endif %} href="{{ url_for('account.setting') }}">
                      <i class="fa fa-cog"></i>
                      <span>修改密码</span>
                  </a>
              </li>
              <li>
                  <a href="{{ url_for('account.signout') }}">
                      <i class="fa fa-key"></i>
                      <span>安全退出</span>
                  </a>
              </li>
          </ul>
          <!-- sidebar menu end-->
      </div>
  </aside>
  <!--sidebar end-->
{% endmacro %}

{% macro form_field(field, display_label=True) %}
  <div class="form-group {% if field.errors %}has-error{% endif %}">
    {% if display_label %}
      {{ field.label }}
    {% else %}
      {{ field.label(class_=('sr-only')) }}
    {% endif %}
    {% if field.description %}
      {{ field(class_='form-control', placeholder=field.description) }}
    {% else %}
      {{ field(class_='form-control') }}
    {% endif %}
    {% if field.errors %}
      <p class="help-block">{{ field.errors[0] }}</p>
    {% endif %}
  </div>
{% endmacro %}

{% macro horizontal_field(field) %}
  <div class="form-group {% if field.errors %}has-error{% endif %}">
    {{ field.label(class_='col-sm-2 control-label') }}
    <div class="col-sm-10">
      {% if field.description %}
        {{ field(class_='form-control', placeholder=field.description) }}
      {% else %}
        {{ field(class_='form-control') }}
      {% endif %}
      {% if field.errors %}
        <p class="help-block">{{ field.errors[0] }}</p>
      {% endif %}
    </div>
  </div>
{% endmacro %}

{% macro horizontal_tag_field(field,class = '') %}
  <div class="form-group {% if field.errors %}has-error{% endif %}">
    {{ field.label(class_='col-sm-2 control-label') }}
    <div class="col-sm-10 {% if class != '' %}{{ class }} {% endif %}">
      {% if field.description %}
          <input class="form-control" id="{{ field.name }}" name="{{ field.name }}" type="text" data-role="tagsinput" value="{{ field.data }}" placeholder="{{ field.description }}">
      {% else %}
          <input class="form-control" id="{{ field.name }}" name="{{ field.name }}" type="text" data-role="tagsinput" value="{{ field.data }}">
      {% endif %}
      {% if field.errors %}
        <p class="help-block">{{ field.errors[0] }}</p>
      {% endif %}
    </div>
  </div>
{% endmacro %}

{% macro horizontal_file_field(field,form_class = '', accept=None) %}
  <div class="form-group {% if form_class != '' %}{{ form_class }} {% endif %} {% if field.errors %}has-error{% endif %}">
    {{ field.label(class_='col-sm-2 control-label') }}
    <div class="col-sm-10">
      {% if accept != None %}
        {{ field(accept=accept) }}
      {% else %}
        {{ field }}
      {% endif %}
      {% if field.description %}
        <p class="help-block">{{ field.description }}</p>
      {% endif %}
      {% if field.errors %}
        <p class="help-block">{{ field.errors[0] }}</p>
      {% endif %}
    </div>
  </div>
{% endmacro %}

{% macro checkbox_field(field) %}
  <div class="checkbox">
    {{ field() }} {{ field.label() }}
  </div>
{% endmacro %}

{% macro radio_field(field, form_class = '') %}
    <div class="form-group {% if form_class != '' %}{{ form_class }} {% endif %} {% if field.errors %}has-error{% endif %}">
        {{ field.label(class_='col-sm-2 control-label') }}
        <div class="col-sm-10">
          {{ field() }}
          {% if field.errors %}
            <p class="help-block">{{ field.errors[0] }}</p>
          {% endif %}
        </div>
    </div>
{% endmacro %}

{% macro pagination(paginator, url) %}
  <ul class="pagination">
    {% for page in paginator.iter_pages() %}
      {% if page %}
        {% if page == paginator.page %}
          <li class="active"><span>{{ page }}</span></li>
        {% else %}
            {% if '?' in url %}
                <li><a href="{{ url }}&page={{ page }}">{{ page }}</a></li>
            {% else %}
                <li><a href="{{ url }}?page={{ page }}">{{ page }}</a></li>
            {% endif %}
        {% endif %}
      {% else %}
        <li class="disabled"><span class="ellipsis">…</span></li>
      {% endif %}
    {% endfor %}
  </ul>
{% endmacro %}

{% macro pager(page, pages, url) %}
  <ul class="pagination">
    <ul class="pagination">
        {% if page > 1 %}
            {% if '?' in url %}
                <li><a href="{{ url }}&page={{ page - 1 }}">上一页</a></li>
            {% else %}
                <li><a href="{{ url }}?page={{ page - 1 }}">上一页</a></li>
            {% endif %}
        {% endif %}
        <li class="disabled"><span>{{ page }}/{{ pages }}</span></li>
        {% if page + 1 < pages %}
            {% if '?' in url %}
                <li><a href="{{ url }}&page={{ page + 1 }}">下一页</a></li>
            {% else %}
                <li><a href="{{ url }}?page={{ page + 1 }}">下一页</a></li>
            {% endif %}
        {% endif %}
    </ul>
  </ul>
{% endmacro %}

{% macro navigation(current='home') %}
    <ul class="nav navbar-nav">
        <li {% if current == 'home' %}class="active"{% endif %}><a href="/">主页</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">校园主页
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                {% for k, v in {'1': '桂电要闻',
                            '2': '校园快讯',
                            '4': '校内通知',
                            '6': '学术会议',
                            '8': '学院动态',
                            '9': '媒体桂电',
                            '10': '公 告'}.items() %}
                    <li><a role="menuitem"
                        href="{{ url_for('college.index', news_type=k) }}">{{ v }}</a> </li>
                {% endfor %}
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">毕业生就业
                    <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                {% for k, v in {3: '就业公告',
                            4: '就业新闻',
                            13: '每周来校招聘单位',
                            15: '用人单位来校招聘信息发布',
                            16: '用人单位网络招聘信息发布'
                            }.items() %}
                    <li><a role="menuitem"
                        href="{{ url_for('work.index', news_type=k) }}">{{ v }}</a> </li>
                {% endfor %}
            </ul>
        </li>
    </ul>
{% endmacro %}

mulan/templates/snippet/markdown-help.html
{% raw %}
<h5>Strong and Emphasize</h5>

<pre><code>*emphasize*    **strong**
_emphasize_    __strong__
</code></pre>

<h5>Links</h5>

<p>Inline links:</p>

<pre><code>[link text](http://url.com/ "title")
[link text](http://url.com/)
&lt;http://url.com&gt;
</code></pre>

<p>Reference-style links:</p>

<pre><code>[link text][id]

    [id]: http://url.com "title"
</code></pre>

<h5>Images</h5>

<p>Inline images:</p>

<pre><code>![alt text](http://path/to/img.jpg "title")
![alt text](http://path/to/img.jpg)
</code></pre>

<p>Reference-style links:</p>

<pre><code>![alt text][id]

    [id]: http://path/to/img.jpg "title"
</code></pre>

<h5>Headers</h5>

<p>Atx-style headers:</p>

<pre><code># h1
## h2
### h5
…
</code></pre>

<p>Closing # are optional.</p>

<pre><code># h1 #
## h2 ##
…
</code></pre>

<h5>Lists</h5>

<p>Ordered list without paragraphs:</p>

<pre><code>1. foo
2. bar
</code></pre>

<p>Unordered list with paragraphs:</p>

<pre><code>* A list item.

  With multiple paragraphs.

* bar
</code></pre>

<p>You can nest them:</p>

<pre><code>* Abacus
  * anser
* Bubbles
  1. bunk
  2. bupkis
     * bar
  3. burper
* Cunning
</code></pre>


<h5>Blockquotes</h5>

<pre><code>&gt; Email-style angle brackets
&gt; are used for blockquotes.

&gt; &gt; And, they can be nested.

&gt; #### Headers in blockquotes
&gt; 
&gt; * You can quote a list.
&gt; * Etc.
</code></pre>

<h5>Code Spans</h5>

<pre><code>`&lt;code&gt;` spans are delimited
by backticks.

You can include literal backticks
like `` `this` ``.
</code></pre>

<h5>Code Blocks</h5>

<p>Indent at least 4 spaces or 1 tab.</p>

<pre><code>This is a normal paragraph

    this is code block
</code></pre>

<p>Fenced code block with three `.</p>
<pre><code>This is a normal paragraph

```
this is code block
```

```python
def foo():
    return True
```
</code></pre>

<h5>Manual Line Breaks</h5>

<p>End a line with two or more spaces:</p>

<pre><code>Roses are red, [space][space]
Violets are blue. [space][space]
</code></pre>
{% endraw %}